# Generated by Django 4.2.5 on 2023-11-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_funding',
            name='after_balance',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='wallet_funding',
            name='amount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='wallet_funding',
            name='previous_balance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='wallet_summary',
            name='after_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet_summary',
            name='amount',
            field=models.IntegerField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='wallet_summary',
            name='previous_balance',
            field=models.IntegerField(default=0),
        ),
    ]
