# Generated by Django 4.2.5 on 2023-11-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_wallet_funding_after_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_summary',
            name='amount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
