# Generated by Django 4.2.5 on 2023-11-09 10:31

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('stereo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='songs/'),
        ),
    ]
