# Generated by Django 4.2.5 on 2023-11-20 09:17

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('stereo', '0004_song_artist_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default='cover-images/default_audio.png', storage=storages.backends.s3.S3Storage(), upload_to='cover-images/'),
        ),
    ]
