# Generated by Django 4.2.5 on 2023-11-11 07:28

import commerce.models
from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='cartId',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=commerce.models.upload_location),
        ),
    ]
