# Generated by Django 4.2.5 on 2023-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Delivered')),
            ],
        ),
    ]
