# Generated by Django 4.2.1 on 2023-10-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='past_question_file',
            field=models.FileField(upload_to='media/past_question'),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.university'),
            preserve_default=False,
        ),
    ]
