# Generated by Django 4.2.1 on 2023-10-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_university_alter_pastquestion_past_question_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestion',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='university_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.pastquestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
