# Generated by Django 4.2.1 on 2023-10-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_pastquestion_university_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='university_question',
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.university'),
            preserve_default=False,
        ),
    ]
