# Generated by Django 4.2.5 on 2023-11-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessdirectory'),
        ),
        migrations.AddField(
            model_name='businessdirectory',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.address'),
        ),
        migrations.AddField(
            model_name='businessdirectory',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.businessownerprofile'),
        ),
        migrations.AddField(
            model_name='businessdirectory',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.phonenumber'),
        ),
    ]
