# Generated by Django 4.2.5 on 2023-09-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.TimeField()),
                ('share', models.IntegerField()),
                ('is_business_post', models.BooleanField(default=False, verbose_name='Business Post')),
                ('is_personal_post', models.BooleanField(default=True, verbose_name='Personal Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(blank=True, default=False, null=True, verbose_name='Like')),
                ('is_dislike', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dislike')),
                ('is_love', models.BooleanField(blank=True, default=False, null=True, verbose_name='Love')),
                ('is_sad', models.BooleanField(blank=True, default=False, null=True, verbose_name='Sad')),
                ('is_angry', models.BooleanField(blank=True, default=False, null=True, verbose_name='Angry')),
                ('is_haha', models.BooleanField(blank=True, default=False, null=True, verbose_name='Haha')),
                ('is_wow', models.BooleanField(blank=True, default=False, null=True, verbose_name='Wow')),
                ('is_others', models.BooleanField(blank=True, default=False, null=True, verbose_name='Others')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.post')),
            ],
        ),
    ]
