# Generated by Django 4.2.5 on 2023-11-15 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_comments', to='feed.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repost',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sharepost',
            name='shared_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='feed.post'),
        ),
        migrations.CreateModel(
            name='Tagged_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
