# Generated by Django 4.2.5 on 2023-11-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_file_remove_post_product_postmedia_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
