# Generated by Django 4.2.5 on 2023-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_comments_alter_post_timestamp_hashtags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repost',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
