# Generated by Django 4.2.5 on 2023-11-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_comment_timestamp_alter_repost_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
    ]
