# Generated by Django 4.2.5 on 2023-11-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_comment_parent_commentmedia_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmedia',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
    ]
