# Generated by Django 4.2.5 on 2023-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_commentmedia_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='media',
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.ManyToManyField(blank=True, null=True, to='feed.commentmedia'),
        ),
    ]
