# Generated by Django 4.2.5 on 2023-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_postmedia_is_business_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='content',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
