# Generated by Django 4.2.5 on 2023-11-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_postmedia_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagged_user',
            name='post',
        ),
    ]
