# Generated by Django 4.2.5 on 2023-12-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_remove_tagged_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='time_since',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
