# Generated by Django 4.2.5 on 2023-12-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_postmedia_time_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public'),
        ),
    ]
