# Generated by Django 4.2.5 on 2023-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reaction',
        ),
        migrations.AddField(
            model_name='comment',
            name='reaction',
            field=models.ManyToManyField(related_name='comment_rection', to='feed.reaction'),
        ),
    ]
