# Generated by Django 4.2.5 on 2023-12-08 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0019_remove_comment_reaction_comment_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='Reaction',
            field=models.ManyToManyField(to='feed.reaction'),
        ),
        migrations.CreateModel(
            name='ReplyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='comment_files/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='media',
            field=models.ManyToManyField(to='feed.replymedia'),
        ),
    ]
