# Generated by Django 4.2.5 on 2023-12-08 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_postmedia_reaction_replymedia_reply_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
