# Generated by Django 4.2.5 on 2023-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_comment_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='file_type',
            field=models.CharField(choices=[('Images', 'Images'), ('Videos', 'Videos'), ('Music', 'Music'), ('Location', 'Location'), ('Recording', 'Recording'), ('PDF', 'PDF'), ('Word', 'Word'), ('Excel', 'Excel'), ('PPT', 'PPT'), ('Files', 'Files'), ('Apk', 'Apk'), ('EXE', 'EXE')], null=True),
        ),
    ]
