# Generated by Django 4.2.5 on 2023-11-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_detection',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='image data'),
        ),
    ]
