# Generated by Django 4.2.5 on 2023-11-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='bonus',
            field=models.IntegerField(default=1, verbose_name='current bonus'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='medium',
            field=models.CharField(choices=[('login', 'login'), ('post_creation', 'post_creation'), ('comments', 'comments'), ('stick', 'stick'), ('likes', 'likes'), ('stickers', 'stickers'), ('time_rewards', 'time_rewards'), ('commerce', 'commerce'), ('start_livestream', 'start_livestream'), ('engage_livestream', 'engage_livestream'), ('buy_tickets', 'buy_tickets'), ('sell_tickets', 'sell_tickets'), ('stereo', 'stereo')], default='login', max_length=50, verbose_name='medium of earning'),
        ),
    ]
