# Generated by Django 4.2.5 on 2023-11-08 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0002_alter_reward_bonus_alter_reward_medium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim_Reward_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claims', models.IntegerField(default=0, verbose_name='total claims')),
                ('total_claims', models.IntegerField(default=0, verbose_name='total claims')),
                ('medium', models.CharField(max_length=256, verbose_name='medium')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='each_user')),
            ],
        ),
    ]
