# Generated by Django 4.2.5 on 2023-09-08 13:42

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=0, max_length=63),
            preserve_default=False,
        ),
    ]
