# Generated by Django 4.2.5 on 2023-09-14 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=250)),
                ('work', models.CharField(max_length=250)),
                ('link1', models.URLField(max_length=250)),
                ('link2', models.URLField(max_length=250)),
                ('link3', models.URLField(max_length=250)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
