# Generated by Django 4.2.5 on 2023-11-11 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usercoverimage_alter_userprofile_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='cover_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
