# Generated by Django 4.2.5 on 2023-09-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='verificationImage/'),
        ),
    ]
