# Generated by Django 4.2.5 on 2023-10-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_updated_profile',
            field=models.BooleanField(default=False),
        ),
    ]
