# Generated by Django 4.2.5 on 2023-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
