# Generated by Django 4.2.5 on 2023-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_address_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeoInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250, null=True)),
                ('city_ascii', models.CharField(max_length=250, null=True)),
                ('lat', models.CharField(max_length=250, null=True)),
                ('lng', models.CharField(max_length=250, null=True)),
                ('country', models.CharField(max_length=250, null=True)),
                ('iso2', models.CharField(max_length=250, null=True)),
                ('iso3', models.CharField(max_length=250, null=True)),
                ('admin_name', models.CharField(max_length=250, null=True)),
                ('capital', models.CharField(max_length=250, null=True)),
                ('population', models.CharField(max_length=250, null=True)),
                ('mid', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
