# Generated by Django 4.2.5 on 2023-12-08 14:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0026_alter_poll_duration'),
        ('user', '0009_usergeoinformation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_address', to='user.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_image', to='user.usercoverimage'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_favorite', to='user.businesscategory'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_updated_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Flagged_User'),
        ),
        migrations.AddField(
            model_name='user',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_media', to='user.userprofileimage'),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Muslim', 'Muslim'), ('Indigenous', 'Indigenous'), ('Others', 'Others')], max_length=20, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='user',
            name='searched_polls',
            field=models.ManyToManyField(blank=True, related_name='user_searched', to='poll.poll'),
        ),
        migrations.AddField(
            model_name='user',
            name='stickers',
            field=models.ManyToManyField(null=True, related_name='sticking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=user.models.generate_random_string),
        ),
    ]
