# Generated by Django 4.2.5 on 2023-12-14 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_media_user_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], default='NGN', max_length=50)),
                ('balance', models.FloatField(default=0)),
                ('prev_balance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_fund', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], default='NGN', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
