# Generated by Django 4.2.5 on 2023-11-09 10:31

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(default='default-audio.png', upload_to='cover-images/')),
                ('audio_file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='songs/')),
            ],
        ),
    ]
