# Generated by Django 4.2.5 on 2023-11-11 07:28

from django.db import migrations, models
import utils.Customstorage


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demosong',
            name='audio_file',
            field=models.FileField(storage=utils.Customstorage.CustomS3Boto3Storage(), upload_to='songs/'),
        ),
    ]
