# Generated by Django 4.2.5 on 2023-11-11 14:28

from django.db import migrations, models
import utils.Customstorage


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_demovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demovideo',
            name='video_file',
            field=models.FileField(storage=utils.Customstorage.CustomS3Boto3Storage(), upload_to='video/'),
        ),
    ]
