# Generated by Django 4.2.5 on 2023-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_geopraphical_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopraphical_location',
            name='X_File',
            field=models.FileField(null=True, upload_to='loacation'),
        ),
        migrations.AlterField(
            model_name='demosong',
            name='cover_image',
            field=models.ImageField(upload_to='cover-images/'),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='IsPrivate',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='IsPublic',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='fee_settings_category',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='location',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='platform',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='price',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='quantity',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='show_remaining_ticket',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='ticket_name',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='geopraphical_location',
            name='websiteurl',
            field=models.CharField(max_length=50, null=True, verbose_name=''),
        ),
    ]
