# Generated by Django 4.2.5 on 2023-11-28 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='access_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.pollmedia'),
        ),
        migrations.AddField(
            model_name='poll',
            name='options',
            field=models.ManyToManyField(related_name='pollsoption', to='poll.option'),
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollview',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.AddField(
            model_name='pollview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='have_Voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('86e2a0df-5132-4803-851d-c77be0eabbc2')),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.AlterUniqueTogether(
            name='pollview',
            unique_together={('user', 'poll')},
        ),
        migrations.CreateModel(
            name='Option_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('option_image', models.ImageField(upload_to='poll-images/')),
                ('total_vote', models.IntegerField(default=0)),
                ('user_voted', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('duration', models.CharField(choices=[('24 hours', '24 Hours'), ('3 days', '3 Days'), ('7 days', '7 Days'), ('14 days', '14 Days'), ('30 days', '30 Days')], max_length=250)),
                ('type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ended', models.BooleanField(default=False, verbose_name='Ended')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('access_requests', models.ManyToManyField(blank=True, related_name='requested_new_polls', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.pollmedia')),
                ('options', models.ManyToManyField(related_name='newpollsoption', to='poll.option')),
                ('options_list', models.ManyToManyField(related_name='optionnew_list', to='poll.option_list')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='options_list',
            field=models.ManyToManyField(related_name='optionnewlist', to='poll.option_list'),
        ),
    ]
