# Generated by Django 4.2.5 on 2023-11-28 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_payment_user_poll_access_requests_poll_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_list',
            name='all_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('7f4caf32-eebd-42a3-acee-b052c6df97ed')),
        ),
    ]
