# Generated by Django 4.2.5 on 2023-11-28 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_option_list_all_vote_alter_vote_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option_list',
            name='total_vote',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('56109057-7a6d-4d7a-9898-454dc1eff9f8')),
        ),
    ]
