# Generated by Django 4.2.5 on 2023-11-28 09:02

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0004_remove_option_list_total_vote_alter_vote_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option_list',
            name='user_voted',
        ),
        migrations.AddField(
            model_name='option_list',
            name='votee',
            field=models.ManyToManyField(related_name='Each_Voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('4799a05b-0c6d-4133-908e-32c269e264ce')),
        ),
    ]
