# Generated by Django 4.2.5 on 2023-11-28 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_remove_option_list_user_voted_option_list_votee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('b5acb725-4a2b-46d3-8a99-d33332b17d08')),
        ),
        migrations.DeleteModel(
            name='NewPoll',
        ),
    ]
