# Generated by Django 4.2.5 on 2023-11-28 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_poll_vote_id_alter_vote_vote_id_delete_newpoll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='have_Voted',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('57594729-44e5-4cca-bc44-4b5c5917e828')),
        ),
    ]
