# Generated by Django 4.2.5 on 2023-11-28 10:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_remove_vote_have_voted_remove_vote_poll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='each_poll', to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('2c9b36d2-f17b-414a-9417-b6e698814422')),
        ),
    ]
