# Generated by Django 4.2.5 on 2023-11-28 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_vote_poll_alter_vote_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('ccfef7d1-e548-463b-a9a2-3149e601035b')),
        ),
    ]
