# Generated by Django 4.2.5 on 2023-11-28 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_vote_all_poll_vote_have_voted_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='all_poll',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('9c6aa560-59ce-441d-91f2-a62edefd07f6')),
        ),
    ]
