# Generated by Django 4.2.5 on 2023-11-28 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_remove_vote_all_poll_alter_vote_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='all_poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='each_poll', to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.UUIDField(default=uuid.UUID('c198efb2-ba4a-41bd-8be1-2d07c17fe8d7')),
        ),
    ]
