# Generated by Django 4.2.5 on 2023-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='vote_id',
            field=models.UUIDField(null=True),
        ),
    ]
