# Generated by Django 4.2.5 on 2023-11-28 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0015_poll_is_editable_alter_voting_vote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instatiate_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('payment_type', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], default='NGN', max_length=200)),
                ('url', models.CharField(max_length=256, null=True)),
                ('is_instantiated', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('ref_no', models.CharField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
