# Generated by Django 4.2.5 on 2023-11-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_instatiate_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='instatiate_payment',
            name='polls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.AlterField(
            model_name='instatiate_payment',
            name='is_instantiated',
            field=models.BooleanField(default=False),
        ),
    ]
