# Generated by Django 4.2.5 on 2023-11-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0017_instatiate_payment_polls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instatiate_payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
