# Generated by Django 4.2.5 on 2023-12-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_account_balance'),
        ('poll', '0020_alter_poll_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_polls', to='user.userprofile'),
        ),
    ]
