# Generated by Django 4.2.5 on 2023-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0021_poll_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
