# Generated by Django 4.2.5 on 2023-12-02 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0022_poll_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
