# Generated by Django 4.2.5 on 2023-12-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0023_poll_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='privacy',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=250),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=250),
        ),
    ]
