# Generated by Django 4.2.5 on 2023-12-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0024_poll_privacy_alter_poll_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='time_duration',
            field=models.DurationField(null=True),
        ),
    ]
