# Generated by Django 4.2.5 on 2023-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0025_poll_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='duration',
            field=models.CharField(choices=[('22 hours', '22 Hours'), ('24 hours', '24 Hours'), ('3 days', '3 Days'), ('7 days', '7 Days'), ('14 days', '14 Days'), ('30 days', '30 Days')], max_length=250),
        ),
    ]
