# Generated by Django 4.2.1 on 2023-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsettings',
            old_name='push_notifications_enabled',
            new_name='enable_notifications',
        ),
        migrations.AlterField(
            model_name='chatsettings',
            name='message_storage_duration',
            field=models.CharField(choices=[('7 days', '7 days'), ('monthly', '1 month'), ('never', 'Never'), ('forever', 'Forever')], default='forever', max_length=10),
        ),
    ]
