# Generated by Django 4.2.5 on 2023-11-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_category_get_ticket_ticket_ticket_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='each_ticket',
            field=models.ManyToManyField(to='ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_ticket', to='ticket.ticket'),
        ),
    ]
