# Generated by Django 4.2.5 on 2023-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_payoutinfo_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_payment',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
