# Generated by Django 4.2.5 on 2023-11-22 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0006_ticket_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('93497ed9-c80b-498f-bf6e-ee1a35104456')),
        ),
        migrations.AddField(
            model_name='ticket_payment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket_payment',
            name='is_initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ticket_Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('error_key', models.UUIDField(default=uuid.UUID('82c45358-cf52-477b-8e7f-5a30033dbd37'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
