# Generated by Django 4.2.5 on 2023-11-22 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_event_event_key_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Sales_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=256, null=True)),
                ('platform', models.CharField(max_length=256, null=True)),
                ('category', models.CharField(max_length=256, null=True)),
                ('location', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=256, null=True)),
                ('ticket', models.CharField(max_length=256, null=True)),
                ('ticket_key', models.CharField(max_length=256, null=True)),
                ('ticket_category', models.CharField(max_length=256, null=True)),
                ('ticket_price', models.CharField(max_length=256, null=True)),
                ('ticket_quantity', models.CharField(max_length=256, null=True)),
                ('ticket_ticket_key', models.CharField(max_length=256, null=True)),
                ('event_key', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticket_payment',
            options={'get_latest_by': 'time_stamp'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('4c212359-cffd-49e4-8bc8-8bd655ab3e18')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('b8c34dae-9be5-46b0-adb7-64344946f626')),
        ),
    ]
