# Generated by Django 4.2.5 on 2023-11-22 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0008_ticket_sales_ticket_alter_ticket_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_sales_ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('14b5c91d-d1a0-4161-8be6-334bed636677')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('aa0c3266-ad2c-437b-8758-b3e1998c2941')),
        ),
    ]
