# Generated by Django 4.2.5 on 2023-11-22 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_sales_ticket_user_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('517f9c5a-c668-4c66-be29-3254313f0614')),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('f52130db-a573-4d30-a0ce-e8b55642b05d')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('8bbd4604-9324-40ad-b0d2-57e26c471460')),
        ),
    ]
