# Generated by Django 4.2.5 on 2023-11-24 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_withdraw_options_withdraw_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('a2b9919c-9a74-49d7-9959-91a3b79ce111')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('ba1f865a-2f8a-46c4-9ec5-e850eca300a1')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('9ceb01e6-f3cb-422c-bb61-95096917286c')),
        ),
    ]
