# Generated by Django 4.2.5 on 2023-11-24 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('a7a3d356-e24a-4bd6-8f92-b260f4f9766b')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('1e045ab2-5b52-488e-98c0-da4c85287342')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('ad9e1ab0-7a2d-4177-8a14-3958e582f5c8')),
        ),
    ]
