# Generated by Django 4.2.5 on 2023-11-24 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('e361a349-6905-4aa6-98b5-45c12287c2a4')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('f267e5a0-bc2c-4a56-bb87-cd4563fed590')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('c65f1d3c-273a-4e46-a11a-bf788c6649f9')),
        ),
    ]
