# Generated by Django 4.2.5 on 2023-11-24 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('46346eb6-33ee-4cd8-97c7-182ed5ca000a')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('02741023-6be0-4b40-a033-2919cdb08d96')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('5e044ba5-ad94-4f13-ada3-86cad8bcdf55')),
        ),
    ]
