# Generated by Django 4.2.5 on 2023-11-25 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('4acc0cf8-4da1-40d3-a009-111afdb584d4')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('f40e52f0-b0b0-42ab-8b90-a9010cdda7c2')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('58ddede6-9740-4cbc-a57c-c9ef7e0e3e71')),
        ),
    ]
