# Generated by Django 4.2.5 on 2023-11-25 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('d819da3b-3f5b-46a1-bcd9-d9726c37b7bc')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('32ebbd6f-daf9-44f7-9bdd-fd3e81ed4e7c')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f477310b-004f-4b9d-aacf-87a353dabf1e')),
        ),
    ]
