# Generated by Django 4.2.5 on 2023-11-26 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('c547a7ac-c957-4e7a-8003-1a528ec7aab0')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('870b8ae3-baca-4a44-baa1-7d01bc916cde')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('058a008d-d254-4dee-8c5c-ffeb18fdd3db')),
        ),
    ]
