# Generated by Django 4.2.5 on 2023-11-26 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('4a987eb5-7637-4360-8985-0b5e8984d89e')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('9b830f09-9e98-4f6e-854f-9947ed13d025')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('0b32978d-03b4-48d0-a532-e5058c8844d9')),
        ),
    ]
