# Generated by Django 4.2.5 on 2023-11-26 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('8bcbfab9-43e7-4b83-9f16-c20fd1cfd377')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('46a72408-acca-4b41-8c6f-6af0980eb15d')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('db6373f3-acf0-444c-b315-d7c5d601a736')),
        ),
    ]
