# Generated by Django 4.2.5 on 2023-11-26 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('c0b73d62-2b7d-4927-99ec-2727215ecb20')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('5b0c48f1-2e70-4ca6-8599-5a1e25113e7c')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f9e6fc32-3d9a-4895-b84e-188e51064d60')),
        ),
    ]
