# Generated by Django 4.2.5 on 2023-11-26 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('9fb505b2-68f3-4962-8265-88e3f313b2f4')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('13c13a1c-003c-4587-b790-2e2891ed78bf')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('12e86f8a-88d0-4dc0-a33d-4b7a194386d6')),
        ),
    ]
