# Generated by Django 4.2.5 on 2023-11-27 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('55e0e249-adac-4111-b7a6-ebdfd01b8c15')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('7809404f-0a7d-4493-b115-8841004a1f36')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('82a26cf4-5822-4eea-93f7-67d527b526d3')),
        ),
    ]
