# Generated by Django 4.2.5 on 2023-11-27 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('d8ff4cb2-9b3a-4bac-a18c-94a6c78dfdf5')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('fef6c50e-9f9a-430a-99e3-8b1f625bc746')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('38d777b2-671f-44fa-8e37-055a3391705a')),
        ),
    ]
