# Generated by Django 4.2.5 on 2023-11-27 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('d065002c-31d0-45c1-bbd5-97f09b094963')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('e3555695-fd42-4cce-973d-7fb978de18a8')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('63d6ce2d-a872-409b-b09b-06ebb1994e6a')),
        ),
    ]
