# Generated by Django 4.2.5 on 2023-11-28 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('861dbb21-979d-4122-8e75-413ededc92f5')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('f1e822ad-e554-4e61-8150-39b3f4e11fb3')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('61c9e2b9-50a4-427d-821d-884a49310d7d')),
        ),
    ]
