# Generated by Django 4.2.5 on 2023-11-28 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('ca62a55f-aafd-4853-ba9e-0688f96807c0')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('52fd38e5-0a4f-4cfe-8f63-8b4789ee9cdf')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f7e3c5af-3547-493d-af35-6e06960bec09')),
        ),
    ]
