# Generated by Django 4.2.5 on 2023-11-28 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0034_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('3fa05c13-c2f0-4a0c-ac60-7f20e875273b')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('dc46a2fc-746f-4141-bb4d-eef8c5a61b1e')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('31545618-c58e-4f3a-b290-0fae92fb7133')),
        ),
    ]
