# Generated by Django 4.2.5 on 2023-11-28 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0035_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('409db100-2aec-41e6-aa1e-af3d28585df9')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('bf66aa6a-a8b6-42e3-862a-9ec1ac368721')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('9b202694-6bbc-4ca8-a05b-21fe7b3edda4')),
        ),
    ]
