# Generated by Django 4.2.5 on 2023-11-28 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0036_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('16ca112b-7488-4bbc-b289-834cd538d568')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('715e5ee6-3bf5-4227-92a3-fdc590f6d647')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('8a4af136-71a6-47e4-95df-06dd0c633bdc')),
        ),
    ]
