# Generated by Django 4.2.5 on 2023-11-28 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('60fa76e3-edd4-44f7-8a97-d3547404b9b0')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('8ebe789e-9327-4c7f-9688-6ecba58a42f4')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('c933de5d-a4e7-4eab-a0df-1372e2f14a4f')),
        ),
    ]
