# Generated by Django 4.2.5 on 2023-11-28 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0039_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('935e38c7-57a3-4102-8ee4-c89b1d518bcb')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('040c9c8a-cc97-4007-87f5-adaef463ef62')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('6369d9a1-5f92-4052-a12c-b3ae8c11fb41')),
        ),
    ]
