# Generated by Django 4.2.5 on 2023-11-28 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('8c4397e7-9b86-4ac0-9111-39b35a6eff2b')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('87605e28-4c1d-4bf2-b887-503803dbe5c3')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('182e61aa-c66b-4618-944f-b7b84a357db2')),
        ),
    ]
