# Generated by Django 4.2.5 on 2023-11-28 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('0b0a3f09-d2bb-4651-8e4c-8e6d8ce78be7')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('e6e076e2-42a4-43f4-9b7a-9f87ba6588cb')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f7e993c3-9c94-469b-8640-76618261a999')),
        ),
    ]
