# Generated by Django 4.2.5 on 2023-11-28 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0043_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('838deff3-8359-4131-b3a4-9b75152b8300')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('8b4d7b8b-bc77-40da-98fa-bc86d26e820d')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('2cbe5efa-07cc-4ec8-ad04-c5cfbf577298')),
        ),
    ]
