# Generated by Django 4.2.5 on 2023-11-28 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0044_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('2e8babcc-a6c4-4a6f-8845-896ba7f37017')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('41efb151-a830-4764-af8c-ebcf2d4b6311')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('7124ec46-c3b0-4e28-ad9b-77b6925f4be7')),
        ),
    ]
