# Generated by Django 4.2.5 on 2023-11-28 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0045_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('61d3dcfe-686f-4360-873f-aa7636e05ff8')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('30864832-b1e9-46d2-8003-11dff42f6aa3')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('ba1f996e-02e0-4754-9efb-c319410f1740')),
        ),
    ]
