# Generated by Django 4.2.5 on 2023-11-28 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0047_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('f80225f1-9384-4732-8247-e1d077aca9fc')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('9ed9fe17-f5dc-4a90-8239-0fc1b5337457')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('2cc8e223-2c1a-4801-b810-d3e8f960034e')),
        ),
    ]
