# Generated by Django 4.2.5 on 2023-11-28 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0048_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('31ee3246-5ed1-4a42-929b-ceadb4b32df7')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('83ea963d-f7fb-417c-9a74-905bedef6162')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f9ef075c-f63b-43e2-ac09-e5fb4c757f0b')),
        ),
    ]
