# Generated by Django 4.2.5 on 2023-11-28 10:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0050_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('f14b9af3-cc7c-499b-a530-c2dd5500f089')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('ae8158f9-5e76-40e9-972c-fd9a0c5ae5e0')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('111db9e8-bef2-444e-bd60-3ddc01ad8bc8')),
        ),
    ]
