# Generated by Django 4.2.5 on 2023-11-28 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0052_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('b2a984a1-a03d-4b17-86e8-56bba9290166')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('6b8af071-d943-4168-9a4e-0c4926ab1f6f')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('3d19765d-291f-4b24-ad9c-fe0958b96bab')),
        ),
    ]
