# Generated by Django 4.2.5 on 2023-11-28 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0056_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('8bb77186-eb64-4b41-9ef7-2bb1cd54d4d9')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('3fe98a8d-decb-43da-bcfc-8535c3cb4817')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('a34fe6bd-4d6c-41ae-b472-7df5b55900b7')),
        ),
    ]
