# Generated by Django 4.2.5 on 2023-11-28 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0057_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('49b4b820-4fba-45ea-b7c4-3f52a32021a2')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('a8b449b5-3d2e-45d5-852c-c86259faee18')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('cfdc4c62-29e0-4dd7-a211-0f53a49bc751')),
        ),
    ]
