# Generated by Django 4.2.5 on 2023-11-28 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0059_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('4c920cd6-4699-4b37-88a9-d884950c9e86')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('44421e34-ada3-4c9c-893f-3ff7297927c2')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('98e9fb60-0e54-4905-86e6-f4bff98cb583')),
        ),
    ]
