# Generated by Django 4.2.5 on 2023-11-29 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0062_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('84eb6e47-7e79-491c-86f4-16a32eccd7e4')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('1767cd91-f275-4a81-9fc4-fa2a8ad9bf52')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('29c7dee6-8d33-41c6-8706-36f263944c71')),
        ),
    ]
