# Generated by Django 4.2.5 on 2023-11-29 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0063_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('1aac53b8-acd0-4427-94c0-0106b09f7336')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('4ab5bb85-53aa-4ace-9495-f5ace64d7441')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('9a8f0d7e-bd9b-476d-b645-fc107e90a602')),
        ),
    ]
