# Generated by Django 4.2.5 on 2023-11-29 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0064_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('9b34deb1-3750-4e0d-b652-9c6ce70d59ef')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('2e7344e2-0c33-4ad0-820f-a90f0b423ee0')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('a48b2643-8c5d-4f4c-bd97-5913a0dbac5a')),
        ),
    ]
