# Generated by Django 4.2.5 on 2023-11-29 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0065_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('44d19899-fa62-47f0-a5a6-7913841166ca')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('e2b1ee1c-6cc7-4a84-ad4a-0cfa63a6c393')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('823c03b2-231c-4d76-9e52-c0ed1a4ad3b9')),
        ),
    ]
