# Generated by Django 4.2.5 on 2023-11-29 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0068_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('9733952c-b4c3-4023-b910-58b433c2dcaf')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('9ec5d478-c2df-43e5-9934-ec8c12a68065')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('2c7046ea-da3a-4f99-9119-dc7bd221eb0d')),
        ),
    ]
