# Generated by Django 4.2.5 on 2023-11-30 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0069_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('cf4bdb4b-06f3-43f3-b573-25c7f4b2227f')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('d83244bf-e2fe-4e58-b30e-7854780565e9')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('654ab1eb-176d-4fe4-a5ae-8544624610e7')),
        ),
    ]
