# Generated by Django 4.2.5 on 2023-11-30 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0070_event_event_id_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('c0ea083d-c199-4015-9bbb-691275e7825f')),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('d4da1f2d-77ce-4e1c-a69a-9d383294431a')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('e14ae74b-4f1b-4fb2-9e7a-8641c9277d07')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('9bf036a0-3e24-488d-a026-1ec5245a2351')),
        ),
    ]
