# Generated by Django 4.2.5 on 2023-11-30 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0072_remove_event_event_id_alter_event_event_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('938bd06e-5a46-4863-a37f-087f69af40f7')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('604e5466-c9b8-4a46-8fa8-aa7d56ed1140')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('429c65a6-0fff-4707-b4a1-c2a51890a6ef')),
        ),
    ]
