# Generated by Django 4.2.5 on 2023-12-01 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0073_alter_event_event_key_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('37233721-2975-4f8b-9126-313cd56e4d8a')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('118e3ea8-9fff-40c6-88e5-33c28fb019df')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('7b28cceb-49a6-4a9d-94bf-d2d695c3d0d0')),
        ),
    ]
