# Generated by Django 4.2.5 on 2023-12-02 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0076_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('84303c24-a41f-4f84-8c81-9a75998e7fb2')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('f0200c94-0d19-417c-afb2-4c2ca0d62e0d')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('a2183b56-de28-41eb-9551-0c08aee5649f')),
        ),
    ]
