# Generated by Django 4.2.5 on 2023-12-02 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0077_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('b6ea53b5-4126-46f0-8147-42c99dbd21e8')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('6b26826c-efe3-4746-aca3-95066c26ee63')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('1132ef7c-0e25-4543-bf75-0b7b3f9add0d')),
        ),
    ]
