# Generated by Django 4.2.5 on 2023-12-02 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0078_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('c8bfbcc6-d3b5-47c0-b075-8c1f8ade91d8')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('34dd792c-0787-4aa4-b248-af5042b4af69')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('ac5f003d-c184-4020-9c37-c19cf163f8d9')),
        ),
    ]
