# Generated by Django 4.2.5 on 2023-12-02 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0080_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('9aa921bf-8091-4db2-af1f-fcb49e569e51')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('49ef866f-6bc0-4ff0-8a84-1d542736c699')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('2f6d1794-1c03-4169-b68c-85e1d071fb00')),
        ),
    ]
