# Generated by Django 4.2.5 on 2023-12-02 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0082_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('ab5d039c-c42e-4d7d-bac7-a333248002ce')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('66222571-039a-48d2-a517-e49f3428b6f5')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('1a1cd184-b8c0-4da7-a506-a61a5d4aba2d')),
        ),
    ]
