# Generated by Django 4.2.5 on 2023-12-02 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0083_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('0f336e0c-f445-4b4d-9fe5-a21e48f4829b')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('4dc177d9-61f4-481f-8feb-ce05bb98dbc9')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('3246d414-d210-431c-999a-cebe32a6114d')),
        ),
    ]
