# Generated by Django 4.2.5 on 2023-12-02 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0086_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('161230cd-b2a1-403c-bb46-7e52bcd5a96e')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('59044ab0-56e8-4119-83c6-4f13434ca825')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('70c9a243-fea0-4f25-953c-d40e362f9826')),
        ),
    ]
