# Generated by Django 4.2.5 on 2023-12-04 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0088_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('f2ffb6d1-3ef1-40cd-85c0-d2108b3ad0c2')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('c69103f9-9840-45d5-901f-f2a7fa083ea2')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('f0246087-9198-4dad-8827-e84c7d4bc75f')),
        ),
    ]
