# Generated by Django 4.2.5 on 2023-12-05 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0090_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('e70b73d9-7674-4360-8b12-aa5bfcc14c7d')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('88e2e594-07c9-4a79-bf8d-bbe332996d88')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('8cf04033-d736-4669-838c-34c7cab5e5e9')),
        ),
    ]
