# Generated by Django 4.2.5 on 2023-12-06 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0091_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('3d010953-37a1-46a1-93c6-98c9f85dda8f')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('94793486-dd5b-469a-bb41-7709f3aadf71')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('7b4adb65-2f54-4000-b27b-4d769ed9aa26')),
        ),
    ]
