# Generated by Django 4.2.5 on 2023-12-06 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0092_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('1fe4c1d1-3e01-40e8-82d9-79e98910ec3c')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('641257fb-cc67-449b-8007-3bd6f1666eb1')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('6ba58764-e6ae-47ca-86f2-9c22ff09466c')),
        ),
    ]
