# Generated by Django 4.2.5 on 2023-12-07 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0093_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('07aa37b3-040e-4d31-a572-82a964c7ad32')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('133b6460-7ed3-4235-bbd3-8efce909dea0')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('8e8ed8ca-cbd6-4a62-ad8e-63beaba70088')),
        ),
    ]
