# Generated by Django 4.2.5 on 2023-12-08 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0094_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('ab1abebb-7b49-44f0-bf8a-c58787f6152f')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('31be288d-8513-4c54-bb00-5cb5ceacd1e5')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('c5734c17-cb0b-4d2a-9b68-0f72c9010fc1')),
        ),
    ]
