# Generated by Django 4.2.5 on 2023-12-08 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0095_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('8e43430d-b175-4eb1-b527-5b1d42714651')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('cc4142e1-84ad-4037-8ec1-5f763f1640dd')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('9f22eb9d-01b3-41f2-afa5-372aa0cc68d4')),
        ),
    ]
