# Generated by Django 4.2.5 on 2023-12-08 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0098_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('dd48ec51-42b2-421f-a7ca-602e53fa9f64')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('7fc9436c-1404-44a9-8b79-50d4fc935453')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('e55129de-2cc4-4fbd-9dd8-c62942d63e3d')),
        ),
    ]
