# Generated by Django 4.2.5 on 2023-12-08 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0099_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('492583bb-ca02-4f70-89a6-4d33ff133906')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('cbec28a0-6c00-448e-8fdf-a8a5c29c3459')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('4c9af920-e585-4a14-bd52-4cbe92e716d3')),
        ),
    ]
