# Generated by Django 4.2.5 on 2023-12-08 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0101_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('4fce8a58-8bd0-4205-a664-5176663bfc37')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('34fa51f9-b2f8-4d4d-bd50-ee2ee55ec0d8')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('bbbc28af-cdd2-45e5-8867-95a0ec0bae47')),
        ),
    ]
