# Generated by Django 4.2.5 on 2023-12-14 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0105_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='add_to_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('2b38a2ca-79dc-4272-820b-7e104640c1e7')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('d5c49908-21cf-49bb-a5ff-e7d413e0a7f2')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('29aae167-c33a-4d40-b167-0eb505799809')),
        ),
    ]
