# Generated by Django 4.2.5 on 2023-12-14 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0107_event_transaction_history_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('b2da38df-949e-4ce9-a4cd-a595b50a8d2d')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('5123accb-0e44-435f-8e90-ebe506f85d5c')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('c4fd2a0f-d3fd-4dd2-b48b-55a02325a906')),
        ),
    ]
