# Generated by Django 4.2.5 on 2023-12-14 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0108_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_transaction_history',
            name='transaction_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('a01e57b9-648b-466d-8e31-f279bd5d6195')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('10e4ca3c-fddc-472c-9738-fec49fc7cf9d')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('28002556-cce2-4e4e-99b9-63721b15cbb9')),
        ),
    ]
