# Generated by Django 4.2.5 on 2023-12-14 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0109_event_transaction_history_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_ticket', to='ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('ee1639eb-0db6-4630-824d-b6219c80a7c2')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('418acfca-e4cc-4263-99fd-7938c560ebe1')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('50c600e0-5c93-4453-935b-e7e5b819641e')),
        ),
    ]
