# Generated by Django 4.2.5 on 2023-12-14 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0110_alter_event_ticket_alter_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sales',
            field=models.ManyToManyField(to='ticket.ticket_payment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('47e1b786-53cc-4ed5-a1f9-9036ce2492b9')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('a45b22ec-fdf8-4e9e-b7a4-f4f218252c06')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('11e9d05c-a67c-410b-b064-4d8e858883f8')),
        ),
    ]
