# Generated by Django 4.2.5 on 2023-12-14 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0111_event_sales_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('8dc06ca4-9568-4ba8-8a20-78b7d2b4c30c')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('b626d812-ccbe-4284-8f61-943bd1985b2e')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('4f306ec0-00a4-428e-a055-4ada67555dad')),
        ),
    ]
