# Generated by Django 4.2.5 on 2023-12-14 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0112_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('feb13924-2684-447b-8f0a-7e6ebb219be8')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('79830fd3-4f0b-4a43-9e59-f797e92fc07f')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('4a5958b0-c47c-4f89-9c98-e395307edc05')),
        ),
    ]
