# Generated by Django 4.2.5 on 2023-12-22 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0116_event_formated_date_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_payment',
            name='ticket_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='formated_date',
            field=models.CharField(default='22 Dec, 2023'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('e3ac6f7b-814f-430a-87b1-3bd162261aa2')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('13896827-7d31-4818-ae0b-16284e60fe77')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('72320044-b44e-46ac-98b8-c3e9f634939d')),
        ),
    ]
