# Generated by Django 4.2.5 on 2023-12-22 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0117_ticket_payment_ticket_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_payment',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('62122533-ef74-44ba-9c47-9d2fa463b1f1')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('aef81657-d9cd-418d-831b-849712974a4d')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('c5a187f5-d25a-4164-88c2-a6a3ed0eb54f')),
        ),
    ]
