# Generated by Django 4.2.5 on 2023-12-23 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0118_ticket_payment_total_amount_alter_ticket_ticket_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='formated_date',
            field=models.CharField(default='23 Dec, 2023'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_key',
            field=models.UUIDField(default=uuid.UUID('edd0c324-1444-4f80-b603-f42fdb40e7e5')),
        ),
        migrations.AlterField(
            model_name='ticket_issues',
            name='error_key',
            field=models.UUIDField(default=uuid.UUID('a986b609-8ca0-4b71-8e83-2f52b1402fe5')),
        ),
        migrations.AlterField(
            model_name='ticket_payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.UUID('d892033b-0b3d-4986-afa0-fccd5bdd501a')),
        ),
    ]
